import { createAztecNodeClient } from "@aztec/aztec.js/node"
import { PXE } from "@aztec/pxe/client/bundle"
import { AztecAddress } from "@aztec/aztec.js/addresses"
import { Fr } from "@aztec/aztec.js/fields"
import { SponsoredFeePaymentMethod } from "@aztec/aztec.js/fee"
import { getContractInstanceFromInstantiationParams } from "@aztec/stdlib/contract"
import { deriveSigningKey } from "@aztec/stdlib/keys"
import { SchnorrAccountContractArtifact } from "@aztec/accounts/schnorr"
import { SponsoredFPCContract, SponsoredFPCContractArtifact } from "@aztec/noir-contracts.js/SponsoredFPC"
import { createPXE, getPXEConfig } from "@aztec/pxe/server"
import { createStore } from "@aztec/kv-store/lmdb"
import { TestWallet } from "@aztec/test-wallet/server"

// Import artifact JSON directly and load it lazily to avoid module load-time errors
// We'll import the artifact when needed instead of at module load time
let AztecGateway7683ContractArtifact: any = null

export async function getAztecGateway7683ContractArtifact() {
  if (!AztecGateway7683ContractArtifact) {
    // Import from the TypeScript artifact file (same as deployment script uses)
    // The deployment script successfully uses this, so it should work here too
    // The artifact is already generated by aztec codegen with proper transpiled bytecode
    const { AztecGateway7683Contract } = await import(
      "../../../aztec/aztec_gateway_7683/src/artifacts/AztecGateway7683.ts"
    )
    AztecGateway7683ContractArtifact = AztecGateway7683Contract.artifact
  }
  return AztecGateway7683ContractArtifact
}

import type { AztecNode } from "@aztec/aztec.js/node"
import type { ContractInstanceWithAddress } from "@aztec/stdlib/contract"
import type { ResolvedOrder } from "../types.js"
import type { AccountWithSecretKey } from "@aztec/aztec.js/account"

type RegisterContractOptions = {
  artifact: any
}

let pxe: PXE
let wallet: TestWallet
let account: AccountWithSecretKey
let accountRegistered = false

export const getAztecWallet = async (): Promise<AccountWithSecretKey> => {
  if (account) {
    return account
  }

  const secretKey = Fr.fromHexString(process.env.AZTEC_SECRET_KEY as string)
  const salt = Fr.fromHexString(process.env.AZTEC_SALT as string)

  // Create account using TestWallet (don't deploy - account already exists on devnet)
  const accountContract = await wallet.createSchnorrAccount(secretKey, salt)
  account = await accountContract.getAccount()

  return account
}

export const initPxe = async () => {
  const node = await getAztecNode()
  const fullConfig = {
    ...getPXEConfig(),
    l1Contracts: await node.getL1ContractAddresses(),
    proverEnabled: process.env.AZTEC_PROVER_ENABLED === "true",
  }
  const store = await createStore("filler-pxe", {
    dataDirectory: "store",
    dataStoreMapSizeKb: 1e6,
  })

  // Create TestWallet instead of raw PXE
  wallet = await TestWallet.create(node, fullConfig, {
    store,
    useLogSuffix: true,
  })

  // Keep reference to PXE for backward compatibility
  pxe = wallet as any
}

export const registerContracts = async ({
  aztecGatewayAddress,
  aztecTokenAddress,
}: {
  aztecGatewayAddress: string
  aztecTokenAddress?: string
}) => {
  await wallet.registerContract({
    instance: await getSponsoredFPCInstance(),
    artifact: SponsoredFPCContractArtifact,
  })
  await wallet.registerSender(AztecAddress.fromString(aztecGatewayAddress))

  // Try to register the gateway contract if it exists on the node
  try {
    const node = await getAztecNode()
    const gatewayInstance = await node.getContract(AztecAddress.fromString(aztecGatewayAddress))

    if (!gatewayInstance) {
      console.warn(`Gateway contract not found on node at ${aztecGatewayAddress}`)
      console.warn("The gateway contract may not be deployed yet on this node.")
    } else {
      // Check if class IDs match
      const { getContractClassFromArtifact } = await import("@aztec/aztec.js/contracts")
      const artifact = await getAztecGateway7683ContractArtifact()
      const artifactClass = await getContractClassFromArtifact(artifact)
      const instanceClassId = gatewayInstance.currentContractClassId

      if (!instanceClassId.equals(artifactClass.id)) {
        console.warn(
          `⚠️  Gateway contract class ID mismatch! ` +
            `Instance: ${instanceClassId.toString()}, ` +
            `Expected: ${artifactClass.id.toString()}. ` +
            `Attempting to get artifact from node...`,
        )
        // Try to get the artifact from the node
        try {
          const classMetadata = await pxe.getContractClassMetadata(instanceClassId, true)
          if (classMetadata?.artifact) {
            await pxe.registerContract({
              instance: gatewayInstance as ContractInstanceWithAddress,
              artifact: classMetadata.artifact,
            })
            console.log(`✅ Registered gateway contract using artifact from node`)
          } else {
            throw new Error("Contract class metadata not available from node")
          }
        } catch (err2: any) {
          console.warn(`Could not get gateway contract class from node: ${err2.message}`)
          // Try registering without artifact - requires artifact to be pre-registered
          try {
            await pxe.registerContract({
              instance: gatewayInstance as ContractInstanceWithAddress,
            })
            console.log(`✅ Registered gateway contract instance (artifact may need to be registered separately)`)
          } catch (err3: any) {
            throw new Error(`Failed to register gateway contract: ${err3.message}`)
          }
        }
      } else {
        // Class IDs match - register normally
        const artifact = await getAztecGateway7683ContractArtifact()
        await registerContractWithoutInstance(AztecAddress.fromString(aztecGatewayAddress), {
          artifact,
        })
        console.log(`✅ Registered gateway contract at ${aztecGatewayAddress}`)
      }
    }
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : String(err)
    console.warn(`Warning: Could not register gateway contract at ${aztecGatewayAddress}: ${errorMessage}`)
    console.warn("The gateway contract may not be deployed yet on this node.")
    console.warn("It will be attempted to register dynamically when needed.")
    // Don't throw - allow the filler to continue and try dynamic registration later
  }

  // Register the deployed token contract if address is provided
  if (aztecTokenAddress) {
    try {
      const { TokenContractArtifact } = await import("@defi-wonderland/aztec-standards/current/artifacts/Token.js")
      const node = await getAztecNode()
      const contractInstance = await node.getContract(AztecAddress.fromString(aztecTokenAddress))

      if (contractInstance) {
        const { getContractClassFromArtifact } = await import("@aztec/aztec.js/contracts")
        const artifactClass = await getContractClassFromArtifact(TokenContractArtifact)
        const instanceClassId = contractInstance.currentContractClassId

        if (!instanceClassId.equals(artifactClass.id)) {
          console.warn(
            `⚠️  Token contract class ID mismatch! ` +
              `Instance: ${instanceClassId.toString()}, ` +
              `Expected: ${artifactClass.id.toString()}. ` +
              `This suggests the token was deployed with a different version of the token contract.`,
          )
          console.warn("Attempting to register with the actual deployed contract class...")

          // Try to get the contract class metadata from the node (with artifact)
          try {
            const classMetadata = await pxe.getContractClassMetadata(instanceClassId, true)
            if (classMetadata?.artifact) {
              // Use the artifact from the node that matches the deployed class ID
              await pxe.registerContract({
                instance: contractInstance as ContractInstanceWithAddress,
                artifact: classMetadata.artifact,
              })
              console.log(
                `✅ Registered token contract using artifact from node (class ID: ${instanceClassId.toString()})`,
              )
            } else {
              throw new Error("Contract class metadata not available from node")
            }
          } catch (err2: any) {
            console.warn(`Could not get contract class from node: ${err2.message}`)
            // Fall back to trying without artifact validation
            await pxe.registerContract({
              instance: contractInstance as ContractInstanceWithAddress,
            })
            console.log(`✅ Registered token contract instance (artifact may need to be registered separately)`)
          }
        } else {
          // Class IDs match - register normally
          await registerContractWithoutInstance(AztecAddress.fromString(aztecTokenAddress), {
            artifact: TokenContractArtifact,
          })
          console.log(`✅ Registered token contract at ${aztecTokenAddress}`)
        }
      }
    } catch (err) {
      console.warn(`Warning: Could not register token contract: ${err instanceof Error ? err.message : err}`)
      console.warn("The token contract may need to be registered dynamically when orders are processed.")
    }
  }
}

export const getPxe = () => {
  return pxe
}

export const getWallet = () => {
  return wallet
}

export const getAztecNode = async (): Promise<AztecNode> => {
  return await createAztecNodeClient(process.env.AZTEC_RPC_URL || "http://localhost:8080")
}

export const getPaymentMethod = async (): Promise<SponsoredFeePaymentMethod> =>
  new SponsoredFeePaymentMethod(await getSponsoredFPCAddress())

export const registerContractWithoutInstance = async (
  address: AztecAddress,
  { artifact }: RegisterContractOptions,
): Promise<void> => {
  const node = await getAztecNode()
  const contractInstance = await node.getContract(address)

  if (!contractInstance) {
    throw new Error(`Contract instance not found for address ${address.toString()}`)
  }

  const instance = contractInstance as ContractInstanceWithAddress
  const instanceClassId = instance.currentContractClassId

  // Check if class IDs match
  const { getContractClassFromArtifact } = await import("@aztec/aztec.js/contracts")
  const artifactClass = await getContractClassFromArtifact(artifact)
  const artifactClassId = artifactClass.id

  if (!instanceClassId.equals(artifactClassId)) {
    // Class IDs don't match - try to register without artifact first
    // This will work if the artifact for this class ID is already registered
    try {
      console.warn(
        `⚠️  Class ID mismatch for contract ${address.toString()}: ` +
          `instance has ${instanceClassId.toString()}, artifact has ${artifactClassId.toString()}. ` +
          `Attempting to register without artifact validation...`,
      )
      // Try registering without artifact - requires artifact to be pre-registered for this class ID
      await pxe.registerContract({
        instance,
      })
      console.log(`✅ Registered contract instance at ${address.toString()} (without artifact validation)`)
      return
    } catch (err: any) {
      // If that fails, try registering the contract class first, then the instance
      if (err.message?.includes("Artifact not found")) {
        console.warn(`Attempting to register contract class first...`)
        try {
          // Register the contract class for the instance's class ID
          // We'll use the artifact we have, even though class IDs don't match
          // This might work if the functions are compatible
          await pxe.registerContractClass(artifact)
          await pxe.registerContract({
            instance,
            artifact,
          })
          console.log(`✅ Registered contract with class ID registration`)
          return
        } catch (err2: any) {
          throw new Error(
            `Failed to register contract: Class ID mismatch (instance: ${instanceClassId.toString()}, artifact: ${artifactClassId.toString()}). ` +
              `The deployed contract may be using a different version of the token contract. ` +
              `Original error: ${err2.message}`,
          )
        }
      }
      throw err
    }
  }

  // Class IDs match - register normally
  await pxe.registerContract({
    instance,
    artifact,
  })
}

export const parseOpenLog = (log1: Fr[], log2: Fr[]) => {
  let orderId1 = log1[0]!.toString()
  const residualBytes1 = log1[12]!.toString()
  const resolvedOrder1 =
    "0x" +
    log1[1]!.toString().slice(4) +
    residualBytes1.slice(6, 8) +
    log1[2]!.toString().slice(4) +
    residualBytes1.slice(8, 10) +
    log1[3]!.toString().slice(4) +
    residualBytes1.slice(10, 12) +
    log1[4]!.toString().slice(4) +
    residualBytes1.slice(12, 14) +
    log1[5]!.toString().slice(4) +
    residualBytes1.slice(14, 16) +
    log1[6]!.toString().slice(4) +
    residualBytes1.slice(16, 18) +
    log1[7]!.toString().slice(4) +
    residualBytes1.slice(18, 20) +
    log1[8]!.toString().slice(4) +
    residualBytes1.slice(20, 22) +
    log1[9]!.toString().slice(4) +
    residualBytes1.slice(22, 24) +
    log1[10]!.toString().slice(4) +
    residualBytes1.slice(24, 26) +
    log1[11]!.toString().slice(4, 44)

  let orderId2 = log2[0]!.toString()
  const residualBytes2 = log2[10]!.toString()
  const resolvedOrder2 =
    log2[1]!.toString().slice(4) +
    residualBytes2.slice(6, 8) +
    log2[2]!.toString().slice(4) +
    residualBytes2.slice(8, 10) +
    log2[3]!.toString().slice(4) +
    residualBytes2.slice(10, 12) +
    log2[4]!.toString().slice(4) +
    residualBytes2.slice(12, 14) +
    log2[5]!.toString().slice(4) +
    residualBytes2.slice(14, 16) +
    log2[6]!.toString().slice(4) +
    residualBytes2.slice(16, 18) +
    log2[7]!.toString().slice(4) +
    residualBytes2.slice(18, 20) +
    log2[8]!.toString().slice(4) +
    residualBytes2.slice(20, 22) +
    log2[9]!.toString().slice(4, 38)

  orderId1 = "0x" + orderId1.slice(4) + residualBytes1.slice(4, 6)
  orderId2 = "0x" + orderId2.slice(4) + residualBytes2.slice(4, 6)

  if (orderId1 !== orderId2) throw new Error("logs don't belong to the same order")

  return {
    orderId: orderId1,
    resolvedOrder: resolvedOrder1 + resolvedOrder2,
  }
}

export const parseResolvedCrossChainOrder = (resolvedOrder: string): ResolvedOrder => {
  return {
    fillInstructions: [
      {
        originData: `0x${resolvedOrder.slice(resolvedOrder.length - 602)}`,
        destinationSettler: `0x${resolvedOrder.slice(resolvedOrder.length - 666, resolvedOrder.length - 602)}`,
        destinationChainId: parseInt(resolvedOrder.slice(resolvedOrder.length - 674, resolvedOrder.length - 666), 16),
      },
    ],
    maxSpent: [
      {
        chainId: parseInt(resolvedOrder.slice(resolvedOrder.length - 682, resolvedOrder.length - 674), 16),
        recipient: `0x${resolvedOrder.slice(resolvedOrder.length - 746, resolvedOrder.length - 682)}`,
        amount: BigInt("0x" + resolvedOrder.slice(resolvedOrder.length - 810, resolvedOrder.length - 746)),
        token: `0x${resolvedOrder.slice(resolvedOrder.length - 874, resolvedOrder.length - 810)}`,
      },
    ],
    minReceived: [
      {
        chainId: parseInt(resolvedOrder.slice(resolvedOrder.length - 882, resolvedOrder.length - 874), 16),
        recipient: `0x${resolvedOrder.slice(resolvedOrder.length - 946, resolvedOrder.length - 882)}`,
        amount: BigInt("0x" + resolvedOrder.slice(resolvedOrder.length - 1010, resolvedOrder.length - 946)),
        token: `0x${resolvedOrder.slice(resolvedOrder.length - 1074, resolvedOrder.length - 1010)}`,
      },
    ],
    orderId: `0x${resolvedOrder.slice(resolvedOrder.length - 1138, resolvedOrder.length - 1074)}`,
    fillDeadline: parseInt(resolvedOrder.slice(resolvedOrder.length - 1146, resolvedOrder.length - 1138), 16),
    openDeadline: parseInt(resolvedOrder.slice(resolvedOrder.length - 1154, resolvedOrder.length - 1146), 16),
    originChainId: parseInt(resolvedOrder.slice(resolvedOrder.length - 1162, resolvedOrder.length - 1154), 16),
    user: `0x${resolvedOrder.slice(resolvedOrder.length - 1226, resolvedOrder.length - 1162)}`,
  }
}

const SPONSORED_FPC_SALT = new Fr(0)

export async function getSponsoredFPCInstance(): Promise<ContractInstanceWithAddress> {
  return await getContractInstanceFromInstantiationParams(SponsoredFPCContract.artifact, {
    salt: SPONSORED_FPC_SALT,
  })
}

export async function getSponsoredFPCAddress() {
  return (await getSponsoredFPCInstance()).address
}

export async function getDeployedSponsoredFPCAddress(pxe: PXE) {
  const fpc = await getSponsoredFPCAddress()
  const contracts = await pxe.getContracts()
  if (!contracts.find((c) => c.equals(fpc))) {
    throw new Error("SponsoredFPC not deployed.")
  }
  return fpc
}
